#define WINDOW_TITLE "Biolab Disaster"
#define WINDOW_WIDTH 400
#define WINDOW_HEIGHT 240

#define GAME_VENDOR "phoboslab"
#define GAME_NAME "biolab"

#define RENDER_WIDTH (WINDOW_WIDTH / 2)
#define RENDER_HEIGHT (WINDOW_HEIGHT / 2)
#define RENDER_RESIZE_MODE RENDER_RESIZE_WIDTH
#define RENDER_SCALE_MODE RENDER_SCALE_DISCRETE

#define ENTITIES_MAX 1024
#define ENTITY_MAX_SIZE 64
#define ENTITY_MIN_BOUNCE_VELOCITY 10

// #define SOUND_MAX_UNCOMPRESSED_SAMPLES (64 * 1024)
// #define SOUND_MAX_SOURCES 64
// #define SOUND_MAX_NODES 256

#define IMAGE_MAX_SOURCES 64

#define RENDER_ATLAS_SIZE 64
#define RENDER_ATLAS_GRID 8
#define RENDER_ATLAS_BORDER 0
#define RENDER_BUFFER_CAPACITY 2048
#define RENDER_TEXTURES_MAX 64

#define ENGINE_MAX_TICK 0.1